version: 0.2

env:
  variables:
    DOCKER_HUB_USERNAME: "wasimakram0028"
    IMAGE_REPO_NAME: "gym-typescript"
    IMAGE_TAG: "v1"
  parameter-store:
    DOCKER_PASSWORD: "/nodejs/docker/password"
    DOCKER_USER: "/nodejs/docker/username"
    DOCKER_REGISTRY_URL: "/nodejs/docker/registry-url"

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL

  build:
    commands:
      - echo "Build started on `date`"
      - FULL_IMAGE_NAME="$DOCKER_HUB_USERNAME/$IMAGE_REPO_NAME:$IMAGE_TAG"
      - docker build -t $FULL_IMAGE_NAME .

  post_build:
    commands:
      - echo "Build completed on `date`"
      - FULL_IMAGE_NAME="$DOCKER_HUB_USERNAME/$IMAGE_REPO_NAME:$IMAGE_TAG"
      - docker push $FULL_IMAGE_NAME
      # Create artifact for the Deploy stage
      - printf '{"ImageTag":"%s"}' $IMAGE_TAG > imageDetail.json

artifacts:
  files:
    - imageDetail.json
    - appspec.yml
    - taskdefinition.json
    - scripts/**/*
    # The above includes the JSON for ECS or the AppSpec for EC2
